### ISSUE TITLE
Add, change or modify available tokens

### ISSUE THREAD

**Issue by jgallagants** [HugoOM/sfdx_autoheader#15]
Hello!

Is there a way to be able to choose which token will be available when adding documentation to a method?

Would it be possible to have the author and date in separate tokens? I would like to know if the order could be changed too.

Thank you very much!!

**Comment by HugoOM** [comment]
Hi @jgallagants!

Thank you for your interest in this project. 

There is currently no way to customize the tags included in the Method Headers, but there is a plan for this feature to be implemented in the future.

You can find those "target" features under the FUTURE section at the top of the [CHANGELOG](https://marketplace.visualstudio.com/items/HugoOM.sfdx-autoheader/changelog)

I had not considered providing customization options for either the order of the tags or splitting the author/date into separate tags, but those are interesting suggestions.

I will keep those in mind next time I go over the roadmap.

Thanks again!
Hugo

**Comment by HugoOM** [comment]
Hi! 

Sorry for the delay, but as they say _better late than never_ :) 

#35 now enables full customization of the File Header properties where you can add/remove some, change the order and set default values.

Hopefully this addresses this ask properly. 

Thanks again for the suggestion!
