### ISSUE TITLE
Feature request - Table's autocomplete

### ISSUE THREAD

**Issue by gvgramazio** [HugoOM/sfdx_autoheader#20]
Right now, when the header is generated, the table is filled with some info and the time stamp of the saving. How I'm supposed to add further rows to the table?

I think that if I should add them manually there is no reason for a time stamp. At most it can be used a date format only. 

A good solution could be to add the rows manually and make the automatic update only of the last row with the time stamp of the invocation of the time stamp.

**Comment by HugoOM** [comment]
Hi @gvgramazio,

I'm really sorry but I'm not sure that I fully understand your suggestion here. 

The update to the time stamps only serves to track when the file was last updated.

Further content to the header has to be added manually. 

Could you please provide more details around your idea so that I can better understand it? 

Thank you!

**Comment by gvgramazio** [comment]
This is how I understood your extension works, so correct me if I'm wrong. If there is no header in the file and I trigger your extension (either manually or in automatic if the corresponding setting is enabled) then it will add the header with a table. It would be good if at each update of the header, your extension will update the time stamp of the last row of the table or the time stamp of the row with the highest version number.

**Comment by HugoOM** [comment]
Thanks for the explanation. 

A time stamp could be added to the last row of the Modification Log at the bottom, but you already have this information with the header level " @Last Modified On" tag, which is updated automatically when the file is saved - and the corresponding setting is enabled. 

Wouldn't the information be redundant in this case or do you see it applying/being triggered in a different way? 

Hugo

**Comment by HugoOM** [comment]
Fixed in #22 by removing the Time component of the changelog entry in the file header template.

Will close the issue for now, but I'll keep in mind and consider implementing a way to have that last entry in the modification log's table updated automatically.

Thanks again for the feedback!
