### ISSUE TITLE
Enable sfdx_autoheader to work with all Apex files

### ISSUE THREAD

**Issue by clarkranderson** [HugoOM/sfdx_autoheader#25]
Hi Hugo,

I am new to the VS Code Marketplace and available extensions.

I just came across the extension in the VS Code Marketplace.

I see it is labelled as "Preview" (Beta). Does that mean that it will only work with the testFile_SFDXAutoheader.apex file you provided?

What are your plans to make it GA for use with Salesforce Apex class files in general? Is there a way to get on the Beta user team.

Any feedback is appreciated!
Thanks

**Comment by HugoOM** [comment]
Hi Clark,

The extension in its current form is meant to, and should, work with any Apex file.

The "testFile_SFDXAutoheader.apex" that you see in the repo is merely there for automated testing of the extension itself. Those aren't part of the "package" that end users can download from the VS Code Extension Marketplace either.

As for the "Preview" flag and "Beta" mention, those are simply there to inform users that the extension is still in its early stage, and that as such, bugs or "wonky" behavior could be experienced, or specific scenarios might not be covered currently. 

Those also help users know that the extension is a work and progress, and serves to encourage them in providing feedback, ideas, or logging issues when they do experience bugs.

Hopefully that clarifies things a bit, do not hesitate to further reach out through this thread, I will let the issue open for a bit before closing.

Thanks,
Hugo

**Comment by clarkranderson** [comment]
Hi Hugo,

Thanks for the prompt reply!

The original "testFile_SFDXAutoheader.apex" works fine, but  "clarkFile_SFDXAutoheader.apex" does not have the SFDoc commands enabled. The "clarkFile_SFDXAutoheader.apex" is just a SaveAs of the original file. For the original file the "Generate Apex Method Helper" and "Insert File Header" commands appear on right-click. The "clarkFile_SFDXAutoheader.apex" is just a SaveAs and does NOT show the commands on right-click.

I tried to attach screen shots of command pallete. Not sure if the will attach.
[SFDoc commands.pdf](https://github.com/HugoOM/sfdx_autoheader/files/3776900/SFDoc.commands.pdf)
[no commands.pdf](https://github.com/HugoOM/sfdx_autoheader/files/3776902/no.commands.pdf)

Looks like a great tool if I could get it to work!

I am new to VS Code extensions, but it works as intended for the original file, not for another Apex file in the same VS Code window.

Any feedback is appreciated!

**Comment by clarkranderson** [comment]
Here are the paths of the saved file:

C:\Users\clark.r.anderson\Documents\sfdx_autoheader\test_files\testFile_SFDXAutoheader\clarkFile_SFDXAutoheader.apex

C:\Users\clark.r.anderson\Documents\sfdx_autoheader\test_files\testFile_SFDXAutoheader\testFile_SFDXAutoheader.apex

You can see that they are in the same directory and are both Apex files. testFile_SFDXAutoheader.apex works as expected. Other file does not.

**Comment by HugoOM** [comment]
Hi @clarkranderson,

The Salesforce Documenter extension relies on the official [Salesforce Extensions for VSCode](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) bundle as a language server, that is to identify which files are of the "Apex" language. 

There are special conditions that ignore this with the "testFile_SFDXAutoheader.apex", again specifically for automated testing purpose, which is why you might be able to currently see the extension working with this file, but not with any other.

Is it possible that you would not have installed this extension bundle yet?

Thanks,
Hugo

**Comment by clarkranderson** [comment]
Hi @HugoOM,

The issue was that VS Code interpreting the ".apex" files I added as Anonymous Apex instead of Apex.

I had to configure the .apex extension to be handled as apex instead of apex-anon.

Thanks for your support!
