### ISSUE TITLE
Add option to choose default date format

### ISSUE THREAD

**Issue by gvgramazio** [HugoOM/sfdx_autoheader#31]
Currently the only format is M/D/YYYY[^1]. It will be good to have other formats as well to avoid ambiguity between month and day.

[^1]: Month-Day-Year with no leading zeros (2/17/2009)

**Comment by HugoOM** [comment]
Hi! 

#35 now allows you to customize the date format with the order and separators of your choosing. 

Month and Days are also left padded now.

Thanks for the suggestion!
