### ISSUE TITLE
Add @Coverage or @TestClass as a default class header var

### ISSUE THREAD

**Issue by DeeTrueSnyder** [HugoOM/sfdx_autoheader#34]
I know this isn't part of a specific spec but in large orgs where naming conventions have changed over time, it can be hard to track down the test classes that cover a specific class or what class is covered by a specific test class. I think the @Coverage var would be best because in non-test classes it can indicate the test class(es) related to the class and in test classes, it can indicate what classes are being covered by the test class. 

Of course, I've seen other request the ability to set your own vars in the headers and implementing that feature would take care of this too, but as I know a ton of devs that use this tool I think it would just be good for everyone to start documenting test class relationship in their classes, but that's just my opinion.

**Comment by HugoOM** [comment]
Hi! 

Thanks for the idea. It is definitely an interesting one and I'm always happy to receive some feedback on how the extension is used and what could be added to it. 

For this specific enhancement, #35 will fix it by enabling full customization of the File Header's properties. 

Thanks again!
