### ISSUE TITLE
Add support for multiple authors

### ISSUE THREAD

**Issue by gvgramazio** [HugoOM/sfdx_autoheader#38]
In #35 you solved issue #19 by updating variable `username` on save. However, while it's good for fields like `last modified by` I don't think that it's also good for fields like `author`. Not only because it has no sense to update the author on each save but also because one cannot save the file without updates without disabling the extension.

IMHO a good solution would be to:

1. Add a checkbox to let the user choose if the update on save is what they want regardless of `EnableForApex`, `EnableForVisualforce`, `EnableForLightningMarkup`, `EnableForLightningJavascript`.
2. Do not update field `author` anymore. Instead, a duplicate field `author` can be added with the new author, if not already present. This will be a behavior similar to the one specified by [java docs best practices](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#@author).

**Comment by HugoOM** [comment]
Fix & enhancement implemented in #39 

Will close this issue for now, but do not hesitate to open up a new one if you find anything else :) 

Thanks again!
