### ISSUE TITLE
Always update file header on save

### ISSUE THREAD

**Issue by domonique-ncino** [HugoOM/sfdx_autoheader#40]
I can never turn this off. I went to settings and unchecked the box to not update the File Header on Save but it still does. I unchecked the box for user and workspace. Only way I can turn it off is if I disable the extension.

**Comment by HugoOM** [comment]
Hi @domonique-ncino,

To do so, you'd have to disable both "Enable for Apex" and the "Always Update on File Save" settings. 

"Always Update on File Save" was intended to be an override for users who wanted existing headers to update, but not for new headers to be insterted on Save. 

I couldn't think of a situation where you'd want to insert new header on Save, if none were present, but not update an existing header.

Please let me know if that addresses your issue. 

I see now that the descriptions for those settings aren't very clear and will adjust those.

I'll also consider making those two actions (and related settings), Inserting & Updating, completely independant and togglable from their own setting, regardless of the other. 

Thank you for your feedback!

**Comment by domonique-ncino** [comment]
This seems to work. Thank you
