### ISSUE TITLE
Make @author (method) and modification log (class) attributes optional 

### ISSUE THREAD

**Issue by jonathanwiesel** [HugoOM/sfdx_autoheader#41]
I love this extension and how it helps developers comply with PMD rules.

Following what is defined in the [PMD ApexDoc Rule](https://pmd.github.io/pmd-6.29.0/pmd_rules_apex_documentation.html) there's a couple attributes that cannot be toggled off in the extension's configuration and are not required by the ApexDoc rule:

* `Modifications Log` in the file header
* `@author` in the method header

Personally I always delete it manually since for me seems like redundant information that you can obtain easily via VCS.

**Comment by HugoOM** [comment]
Hi @jonathanwiesel, 

Thank you for the feedback. I agree with you on both. 

It was already planned to make the "Modification Logs" toggleable through a settings flag, and eventually I'd lake to make the Method header fully customizable - much like the current Class Header. 

Thanks again,
Hugo

**Comment by jonathanwiesel** [comment]
Hi there, any news regarding this?

**Comment by dschach** [comment]
While @author is not required by PMD, it is still a good thing to put in. See ApexDox for a list of often-supported attributes.

A customizable method header would be great too.

**Comment by HugoOM** [comment]
Archiving repository. Thanks for your input.
