### ISSUE TITLE
Not an issue - a question on file header properties

### ISSUE THREAD

**Issue by molsi01** [HugoOM/sfdx_autoheader#42]
Apologies for logging this as an issue, I couldn't find a 'comments' section.
Is it possible to disable this info in the file header?
* Ver   Date               Author              Modification
 * 1.0   16-12-2020   XXXXXXXXX   Initial Version

It isn't mentioned anywhere in the settings or the settings.json file.

Thanks.

**Comment by HugoOM** [comment]
Hi @molsi01, 

It currently isn't possible, but that is in the plan (captured under #41). 

Thanks,
Hugo
