### ISSUE TITLE
Add support for class attributes

### ISSUE THREAD

**Issue by Shandalar** [HugoOM/sfdx_autoheader#43]
Hi Hugo.
In a similar way to how it is done with the methods of the classes, it should also be possible to request the documentation of the attributes.

Good work and best regards

**Comment by HugoOM** [comment]
Hi @Shandalar,

Thanks for the feedback. 

I'm not exactly sure what you meant by documenting a class' attributes through the extension and I'd like to hear more about this idea.

The interest of having the extension automatically document methods is to standardize the format as well as to save time. 

In the case of a single attribute, I always felt that VSCode's auto-closing multi-lines comments covered that usecase. 
```java
  /**
   * Sample Apex class' attribute
   */
  private final static String attribute = 'some_attrib';
``` 

Would there be more to cover that the extension could provide as added value? What did you have in mind? 

Thanks again for the suggestion and for your time!
Hugo

**Comment by HugoOM** [comment]
Hi @Shandalar, 

Given that this issue has been pending for a while without further updates, I will close it down for now. 

You're welcome to open a new one on that same topic if you ever get to it :) 

Thanks again,
Hugo
