### ISSUE TITLE
JSDoc (and ApexDoc) standards don't allow a colon in the property list

### ISSUE THREAD

**Issue by dschach** [HugoOM/sfdx_autoheader#50]
https://github.com/HugoOM/sfdx_autoheader/blob/a73aad8e4cfbc7568fc71ff605cbeb6223cb9be9/src/extension/documenter.helper.ts#L49

Please remove the colon so that 
```
 * @description  : <file_description>
 * @author       :  <author_name>
```
becomes
```
 * @description  <file_description>
 * @author       <author_name>
```

**Comment by HugoOM** [comment]
Archiving repository. Thanks for your input.
